title: Xi Yang (Ian) AMRSC
email: ian16yang@gmail.com
description: >-
  Portfolio for Xi Yang (Ian) AMRSC, a PhD student in computational biology at
  the University of Edinburgh working on single-cell dynamics, stochastic
  modelling, and machine learning for biological time series.
baseurl: ""
url: "https://grignardreagent.github.io"
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

author:
  name: Xi Yang (Ian) AMRSC
  bio: PhD student in computational biology at the University of Edinburgh and PRIMED.
  twitter: Xi_Yang_Ian
  linkedin: https://www.linkedin.com/in/ianyangxi/
  github: https://github.com/GrignardReagent
